pipeline:
  name: Build tf-native
  identifier: Build_tf_native_1686339922190
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build Archetype
        identifier: Build_Archetype
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "create group"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: create_namespace
        identifier: create_namespace
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: create_namespace
                  identifier: create_namespace
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: exit 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
