pipeline:
  name: Build tf-native
  identifier: Build_tf_native_1686339922190
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build Archetype
        identifier: Build_Archetype
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: Create TFC WS
                  identifier: Create_TFC_WS
                  spec:
                    url: https://app.terraform.io/api/v2
                    method: POST
                    headers:
                      - key: Authorization
                        value: <+secrets.getValue("terr")>
                      - key: Content-Type
                        value: application/vnd.api+json
                    inputVariables: []
                    outputVariables: []
                    requestBody: |2-
                              {
                                  "data": {
                                      "type": "workspaces",
                                      "attributes": {
                                          "name": name,
                                          "auto-apply": "true",
                                          "resource-count": "0",
                                          "speculative-enabled": "false",
                                          "terraform-version": "~> 1.3.0",
                                          "working-directory": "",
                                          "file-triggers-enabled": "true",
                                          "trigger-patterns": ["no-action-required"],
                                          "vcs-repo": {
                                              "identifier":"asaharland/tf-native",
                                              "branch":"master",
                                          },
                                      },
                                  }
                              }
                  timeout: 10s
              - step:
                  type: TerraformPlan
                  name: TF Plan
                  identifier: TF_Plan
                  spec:
                    provisionerIdentifier: qa123
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: account.Github_OAuth_1686339878189
                            repoName: asaharland/tf-native
                            gitFetchType: Branch
                            branch: master
                            folderPath: /logs
                          type: Github
                      secretManagerRef: My_TF
                      skipRefreshCommand: false
                  timeout: 10m
        tags: {}
